ignoredBuiltDependencies:
  - es5-ext

onlyBuiltDependencies:
  - '@apollo/protobufjs'
  - '@biomejs/biome'
  - better-sqlite3
  - bufferutil
  - esbuild
  - protobufjs
  - sharp
  - styled-components
