version: "3.8"

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: ai_ysh
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  minio:
    image: minio/minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data

  ollama:
    image: ollama/ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama

  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - POSTGRES_URL=postgresql://user:password@postgres:5432/ai_ysh
      - REDIS_URL=redis://redis:6379
      - BLOB_READ_WRITE_TOKEN=minioadmin:minioadmin@minio:9000/ai-ysh
      - AI_GATEWAY_API_KEY=local
      - AUTH_SECRET=1cf80e79340ab2e22be315f0694436d47976fe1e3c1fc175d5329a0fbb49e6e8
    depends_on:
      - postgres
      - redis
      - minio
      - ollama
    volumes:
      - .:/app
      - /app/node_modules

volumes:
  postgres_data:
  redis_data:
  minio_data:
  ollama_data:
